version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:567234@postgres_db:5432/contacts_app
      - JWT_SECRET=supersecretkey
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw12
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  volumes:
    postgres_data:

  fastapi_app:
    build: .
    env_file:
      - .env
